apiVersion: v1
kind: Secret
metadata:
  name: endpoint-secret
  labels:
    app: containerized-data-importer
type: Opaque
data:
  accessKeyId: "ZHlsYW5zY2htaXR0bGUK"  # <optional: your key or user name, base64 encoded>
  secretKey:  "ZnVja3RydW1wCg==" # <optional: your secret or password, base64 encoded>