apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: jvb
  name: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jvb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/meet.jitsi: "true"
        io.kompose.service: jvb
    spec:
      containers:
      - image: jitsi/jvb:latest
        imagePullPolicy: Always
        name: jvb
        ports:
        - containerPort: 10000
          protocol: UDP
        - containerPort: 4443
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: jvb-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: config-vol
        configMap:
          name: my-config
      - name: jvb-claim0
        persistentVolumeClaim:
          claimName: jvb-claim0
status: {}
