apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: prosody
  name: prosody
spec:
  ports:
  - name: "5222"
    port: 5222
    targetPort: 5222
  - name: "5347"
    port: 5347
    targetPort: 5347
  - name: "5280"
    port: 5280
    targetPort: 5280
  selector:
    io.kompose.service: prosody
status:
  loadBalancer: {}
