apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-blackarch-datavolume
  name: vmi-blackarch
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: datavolumedisk1
    machine:
      type: ""
    resources:
      requests:
        memory: 1Gi
  terminationGracePeriodSeconds: 0
  volumes:
  - name: datavolumedisk1
    dataVolume:
      name: blackarch-dv