apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f etherpad.yml
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: etherpad
  name: etherpad
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etherpad
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f etherpad.yml
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/meet.jitsi: "true"
        io.kompose.service: etherpad
    spec:
      containers:
      - image: jitsi/etherpad:latest
        imagePullPolicy: Always
        name: etherpad
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
