sversion: '3'

services:
    etherpad:
        image: jitsi/etherpad:latest
        restart: always
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
